### ISSUE TITLE
Can't run with latest pygame version (2.6.1)

### ISSUE THREAD

**Issue by frotaur** [MyreMylar/pygame_gui#726]
**Describe the bug**
Pygame_gui crashes when running it alongside pygame 2.6.1. Here is the error message:
```> python .\test_pygame_gui.py                                                                                                    
pygame 2.6.1 (SDL 2.28.4, Python 3.13.7)                                                                                                                                     
Hello from the pygame community. https://www.pygame.org/contribute.html                                                                                                      
Traceback (most recent call last):
  File "C:\Users\vassi\Desktop\Work\PyCA\test_pygame_gui.py", line 2, in <module>
    import pygame_gui
  File "C:\Users\vassi\Desktop\Work\PyCA\bugenv\Lib\site-packages\pygame_gui\__init__.py", line 8, in <module>
    from pygame_gui.ui_manager import UIManager
  File "C:\Users\vassi\Desktop\Work\PyCA\bugenv\Lib\site-packages\pygame_gui\ui_manager.py", line 9, in <module>
    from pygame_gui.core.interfaces import IUIManagerInterface
  File "C:\Users\vassi\Desktop\Work\PyCA\bugenv\Lib\site-packages\pygame_gui\core\__init__.py", line 1, in <module>
    from pygame_gui.core.ui_appearance_theme import UIAppearanceTheme
  File "C:\Users\vassi\Desktop\Work\PyCA\bugenv\Lib\site-packages\pygame_gui\core\ui_appearance_theme.py", line 12, in <module>
    from pygame_gui.core.interfaces.gui_font_interface import IGUIFontInterface
  File "C:\Users\vassi\Desktop\Work\PyCA\bugenv\Lib\site-packages\pygame_gui\core\interfaces\__init__.py", line 4, in <module>
    from pygame_gui.core.interfaces.font_dictionary_interface import (
        IUIFontDictionaryInterface,
    )
  File "C:\Users\vassi\Desktop\Work\PyCA\bugenv\Lib\site-packages\pygame_gui\core\interfaces\font_dictionary_interface.py", line 3, in <module>
    from pygame import DIRECTION_LTR
ImportError: cannot import name 'DIRECTION_LTR' from 'pygame' (C:\Users\vassi\Desktop\Work\PyCA\bugenv\Lib\site-packages\pygame\__init__.py)```

**To Reproduce**
Steps to reproduce the behaviour:
Run the following code with pygame 2.6.1 installed, on Windows:
```
import pygame
import pygame_gui

pygame.init()
WINDOW_SIZE = (800, 600)
screen = pygame.display.set_mode(WINDOW_SIZE, pygame.RESIZABLE)
manager = pygame_gui.UIManager(WINDOW_SIZE)

# Main game loop
clock = pygame.time.Clock()
running = True

while running:
    time_delta = clock.tick(60) / 1000.0

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        manager.process_events(event)

    manager.update(time_delta)

    screen.fill((30, 30, 30))
    manager.draw_ui(screen)

    pygame.display.update()

pygame.quit()
```

**Expected behaviour**
Should not crash.


**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version 0.6.14
 - Pygame version 2.6.1

**Additional context**
Works fine with Pygame 2.5.x

**Comment by frotaur** [comment]
Nevermind just realized there is pygame and pygame-ce :o. The more you know.
